name: lint 
on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        govers: [ 1.14, 1.16 ]
    steps:

    - name: Set up Go version
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.govers }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        GOBIN=$PWD/bin make all